"""Indexing entry point for the Code du travail RAG corpus."""

from __future__ import annotations

import argparse
import json
from typing import Any

from chunking import chunk_documents
from config import AppConfig, load_config
from corpus_loader import load_corpus
from document_parser import DEFAULT_OUTPUT_FILENAME, parse_corpus
from vector_store import index_chunks


class IndexPipelineError(Exception):
    """Raised when indexing cannot be completed."""


def load_processed_documents(
    config: AppConfig,
    filename: str = DEFAULT_OUTPUT_FILENAME,
) -> list[dict[str, Any]]:
    """Load processed documents generated by ``document_parser``."""

    path = config.paths.processed_data_dir / filename
    if not path.is_file():
        raise IndexPipelineError(f"Processed documents file not found: {path}")

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise IndexPipelineError(f"Processed documents file is not valid JSON: {path}") from exc

    documents = payload.get("documents")
    if not isinstance(documents, list):
        raise IndexPipelineError(f"Processed documents file is missing a documents list: {path}")

    return documents


def build_chunks_from_processed_documents(config: AppConfig) -> list[dict[str, Any]]:
    """Build Chroma-ready chunks from processed documents."""

    documents = load_processed_documents(config)
    chunks = chunk_documents(documents)
    return [
        {
            "id": chunk.id,
            "text": chunk.text,
            "metadata": {
                **chunk.metadata,
                "document_id": chunk.document_id,
            },
        }
        for chunk in chunks
    ]


def index_processed_corpus(config: AppConfig | None = None, recreate: bool = False) -> int:
    """Index the already processed corpus into ChromaDB."""

    active_config = config or load_config()
    chunks = build_chunks_from_processed_documents(active_config)
    return index_chunks(chunks, config=active_config, recreate=recreate)


def run_indexing_pipeline(
    config: AppConfig | None = None,
    fetch_raw: bool = False,
    parse_raw: bool = False,
    recreate: bool = False,
) -> int:
    """Run the requested indexing steps and return the indexed chunk count."""

    active_config = config or load_config()

    if fetch_raw:
        load_corpus(config=active_config)

    if parse_raw:
        parse_corpus(config=active_config)

    return index_processed_corpus(config=active_config, recreate=recreate)


def main() -> int:
    parser = argparse.ArgumentParser(description="Prepare and index the RAG corpus.")
    parser.add_argument("--fetch-raw", action="store_true", help="Download raw corpus from Legifrance.")
    parser.add_argument("--parse-raw", action="store_true", help="Parse raw corpus before indexing.")
    parser.add_argument("--recreate", action="store_true", help="Recreate the Chroma collection.")
    args = parser.parse_args()

    count = run_indexing_pipeline(
        fetch_raw=args.fetch_raw,
        parse_raw=args.parse_raw,
        recreate=args.recreate,
    )
    print(f"Indexed {count} chunks into ChromaDB.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
